### ISSUE TITLE
Multiple Locations: `Config error: 'location_idx' = 1, but the valid range is ...`

### ISSUE THREAD

**Issue by HonestJohn61** [zxdavb/evohome-async#14]
Hi, Thanks for doing the work on developing this solution. I followed the instruction carefully, including the check items, but it seems something failed. I'm running HA in a Docker container on a Synology NAS with a macvlan IP address. I logged in as root to the container using Portainer's container console to execute the various instructions. Below are the error logs, summary and detailed. I've also attached an extract from my **configuration.yaml** and the session. Any help much appreciated.

### **Summary**
```
Setup failed for custom integration 'evohome_1': Integration failed to initialize.
10:23:37 PM – (ERROR) setup.py
Config error: 'location_idx' = 1, but the valid range is 0-0. Unable to continue. Fix any configuration errors and restart HA
10:23:37 PM – (ERROR) evohome_1 (custom integration)
```
### **configuration.yaml redacted extract**

```yaml
evohome:
  username: "username1"
  password: "password1"
  location_idx: 0

evohome_1:
  username: "username2"
  password: "password2" [Includes special characters &#%+]
  location_idx: 1
```

### Checking the custom_component changes:
```
67ab0b7e9d3b:/config/custom_components/evohome_1# **cat manifest.json**
{
  "version": "0.0.1",
  "domain": "evohome_1",
  "name": "Honeywell Total Connect Comfort (Europe)",
  "codeowners": ["@zxdavb"],
  "documentation": "https://www.home-assistant.io/integrations/evohome",
  "iot_class": "cloud_polling",
  "loggers": ["evohomeasync", "evohomeasync2"],
  "requirements": ["evohome-async==0.4.6"]
}

67ab0b7e9d3b:/config/custom_components/evohome_1# **cat const.py | grep 'DOMAIN'**
DOMAIN = "evohome_1"
STORAGE_KEY = DOMAIN
```
